# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hari/Desktop/PhD/MathKernelSYCL/src/CG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hari/Desktop/PhD/MathKernelSYCL/src/CG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hari/Desktop/PhD/MathKernelSYCL/src/CG/CMakeFiles /home/hari/Desktop/PhD/MathKernelSYCL/src/CG//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hari/Desktop/PhD/MathKernelSYCL/src/CG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cg

# Build rule for target.
cg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cg
.PHONY : cg

# fast build rule for target.
cg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/build
.PHONY : cg/fast

#=============================================================================
# Target rules for targets named cg_usm

# Build rule for target.
cg_usm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cg_usm
.PHONY : cg_usm

# fast build rule for target.
cg_usm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/build
.PHONY : cg_usm/fast

#=============================================================================
# Target rules for targets named cg_nd_range

# Build rule for target.
cg_nd_range: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cg_nd_range
.PHONY : cg_nd_range

# fast build rule for target.
cg_nd_range/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/build
.PHONY : cg_nd_range/fast

#=============================================================================
# Target rules for targets named cg_nd_range_usm

# Build rule for target.
cg_nd_range_usm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cg_nd_range_usm
.PHONY : cg_nd_range_usm

# fast build rule for target.
cg_nd_range_usm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/build
.PHONY : cg_nd_range_usm/fast

cg.o: cg.cpp.o
.PHONY : cg.o

# target to build an object file
cg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/cg.cpp.o
.PHONY : cg.cpp.o

cg.i: cg.cpp.i
.PHONY : cg.i

# target to preprocess a source file
cg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/cg.cpp.i
.PHONY : cg.cpp.i

cg.s: cg.cpp.s
.PHONY : cg.s

# target to generate assembly for a file
cg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/cg.cpp.s
.PHONY : cg.cpp.s

cg_nd_range.o: cg_nd_range.cpp.o
.PHONY : cg_nd_range.o

# target to build an object file
cg_nd_range.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/cg_nd_range.cpp.o
.PHONY : cg_nd_range.cpp.o

cg_nd_range.i: cg_nd_range.cpp.i
.PHONY : cg_nd_range.i

# target to preprocess a source file
cg_nd_range.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/cg_nd_range.cpp.i
.PHONY : cg_nd_range.cpp.i

cg_nd_range.s: cg_nd_range.cpp.s
.PHONY : cg_nd_range.s

# target to generate assembly for a file
cg_nd_range.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/cg_nd_range.cpp.s
.PHONY : cg_nd_range.cpp.s

cg_nd_range_usm.o: cg_nd_range_usm.cpp.o
.PHONY : cg_nd_range_usm.o

# target to build an object file
cg_nd_range_usm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/cg_nd_range_usm.cpp.o
.PHONY : cg_nd_range_usm.cpp.o

cg_nd_range_usm.i: cg_nd_range_usm.cpp.i
.PHONY : cg_nd_range_usm.i

# target to preprocess a source file
cg_nd_range_usm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/cg_nd_range_usm.cpp.i
.PHONY : cg_nd_range_usm.cpp.i

cg_nd_range_usm.s: cg_nd_range_usm.cpp.s
.PHONY : cg_nd_range_usm.s

# target to generate assembly for a file
cg_nd_range_usm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/cg_nd_range_usm.cpp.s
.PHONY : cg_nd_range_usm.cpp.s

cg_usm.o: cg_usm.cpp.o
.PHONY : cg_usm.o

# target to build an object file
cg_usm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/cg_usm.cpp.o
.PHONY : cg_usm.cpp.o

cg_usm.i: cg_usm.cpp.i
.PHONY : cg_usm.i

# target to preprocess a source file
cg_usm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/cg_usm.cpp.i
.PHONY : cg_usm.cpp.i

cg_usm.s: cg_usm.cpp.s
.PHONY : cg_usm.s

# target to generate assembly for a file
cg_usm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/cg_usm.cpp.s
.PHONY : cg_usm.cpp.s

functions.o: functions.cpp.o
.PHONY : functions.o

# target to build an object file
functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/functions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/functions.cpp.o
.PHONY : functions.cpp.o

functions.i: functions.cpp.i
.PHONY : functions.i

# target to preprocess a source file
functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/functions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/functions.cpp.i
.PHONY : functions.cpp.i

functions.s: functions.cpp.s
.PHONY : functions.s

# target to generate assembly for a file
functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/functions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/functions.cpp.s
.PHONY : functions.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg.dir/build.make CMakeFiles/cg.dir/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_usm.dir/build.make CMakeFiles/cg_usm.dir/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range.dir/build.make CMakeFiles/cg_nd_range.dir/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cg_nd_range_usm.dir/build.make CMakeFiles/cg_nd_range_usm.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cg"
	@echo "... cg_nd_range"
	@echo "... cg_nd_range_usm"
	@echo "... cg_usm"
	@echo "... cg.o"
	@echo "... cg.i"
	@echo "... cg.s"
	@echo "... cg_nd_range.o"
	@echo "... cg_nd_range.i"
	@echo "... cg_nd_range.s"
	@echo "... cg_nd_range_usm.o"
	@echo "... cg_nd_range_usm.i"
	@echo "... cg_nd_range_usm.s"
	@echo "... cg_usm.o"
	@echo "... cg_usm.i"
	@echo "... cg_usm.s"
	@echo "... functions.o"
	@echo "... functions.i"
	@echo "... functions.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

